version: '3.5'

services: 
  service_jekyll:
    image: jekyll/jekyll:4.0.0
    container_name: jekyll_blog
    ports: 
      - 4000:4000
    volumes: 
      - ./:/blog
    command: /blog/start_jekyll_for_develop.sh
