@startuml

abstract Agile

class Scrum
class "XP Programing" as XP

interface "Practice"

interface "やり方？" as Move
interface "Frame?" as Frame

Agile <|-- Scrum
Agile <|-- XP

Scrum o-d- Practice
XP o-d- Practice

Move <|.. Agile
Frame <|.. Scrum

Practice <|.. PairPro
Practice <|.. TDD
Practice <|.. Refactaring

Practice o-- Practice

@enduml
